In [14]:
import pandas as pd
import os
from tqdm import tqdm

In [12]:
data = pd.read_csv("old_inventory.txt", sep="  ", names=["Type", "Key", "Name"],
                   converters={"Type": lambda x: x.rstrip("_").capitalize(),
                               "Key": lambda x: x.rstrip("_").capitalize(),
                               "Name": lambda x: x.title()})

/tmp/ipykernel_16571/2414518946.py:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  data = pd.read_csv("old_inventory.txt", sep="  ", names=["Type", "Key", "Name"],

In [16]:
separator = "-"*50
for s in ["Type", "Key"]:
    print(pd.DataFrame(data[s].value_counts()))
    print(separator)

       count
Type
Reel     193
Jig       98
Other     66
--------------------------------------------------
     count
Key
D       89
Am      56
A       53
G       40
Bm      36
Em      30
Dm      16
F#m     14
E       11
C        4
F        3
Gm       3
C#m      2
--------------------------------------------------

In [17]:
data.to_html(buf="inventory_test.html", index=False, table_id="inventory_table", classes=["display compact"], border=False)

In [20]:
data.to_csv(path_or_buf="new_inventory.csv", index=False)

In [3]:
new_data = pd.read_csv("new_inventory3.csv", sep="|")

In [12]:
new_data.insert(3, "Composer", "")
new_data.insert(1, "Time", "")
new_data.insert(5, "Source(s)", "")
new_data.insert(6, "ABC", "")

In [5]:
new_data.insert(2, "Time Unit", "")

In [6]:
new_data

,Type,Time,Time Unit,Key,Name,Composer,Source(s),ABC
0,Jig,6/8,,F#m,Hold Up the Sky,Brian Finnegan,Jamie Quinn,NaN
1,Jig,NaN,,E,Aj'S,NaN,NaN,NaN
2,Jig,NaN,,D,Arthur Darley'S Swedish Jig,NaN,NaN,NaN
3,Jig,NaN,,F#m,Apsley Cottage,NaN,NaN,NaN
4,Jig,NaN,,A,"Atholl Highlanders, The",NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
352,Other,NaN,,D,"View From The Reek, The",NaN,NaN,NaN
353,Other,NaN,,E,Washington Square Park,NaN,NaN,NaN
354,Other,NaN,,Bm,Wrong Foot Forward,NaN,NaN,NaN
355,Other,NaN,,Am,Yesterhouse,NaN,NaN,NaN
356,Other,NaN,,A,Youngest Ancient Mariner,NaN,NaN,NaN

In [4]:
new_data.to_csv(path_or_buf="new_inventory4.csv", index=False, sep="*")

In [ ]:
new_data = pd.read_csv("new_inventory.csv")
new_data.to_html(buf="inventory_test.html", index=False, table_id="tunelist_table", classes=["display compact"], border=False)

In [2]:
os.listdir("./Tunes")

['arthur_darleys_swedish.abc', 'ajs.abc', 'hold_up_the_sky.abc']

In [5]:
data = pd.DataFrame(columns=["Type", "Time", "Time Unit", "Key", "Name", "Composer", "Source", "ABC"])

In [8]:
"hulk"[2:]

'lk'

In [40]:
tune_list = []
tune_dir = os.path.join(".", "Tunes")
tune_files = os.listdir(tune_dir)
for i in tqdm(range(len(tune_files))):
    tune_file = tune_files[i]
    tune_dict = {"ABC": []}
    with open(os.path.join(tune_dir, tune_file)) as open_tune_file:
        lines = open_tune_file.readlines()
        line_starts = {"X:": {"Found": False, "Name": "X"}, 
                       "T:": {"Found": False, "Name": "Title"}, 
                       "C:": {"Found": False, "Name": "Composer"}, 
                       "M:": {"Found": False, "Name": "Time"}, 
                       "R:": {"Found": False, "Name": "Type"}, 
                       "L:": {"Found": False, "Name": "Time Unit"}, 
                       "S:": {"Found": False, "Name": "Source"}, 
                       "K:": {"Found": False, "Name": "Key"}}
        line_tracker = [False]*8
        for line in lines:
            categorised_line = False
            for line_start in line_starts:
                if categorised_line == False:
                    if line[:2] == line_start:
                        if line_starts[line_start]["Found"] == True:
                            raise RuntimeError("Duplicate of \"{}\" property found in \"{}\"".format(line_start, tune_file))
                        else:
                            line_starts[line_start]["Found"] = True
                            tune_dict[line_starts[line_start]["Name"]] = line[2:].strip()
                            categorised_line = True
            if categorised_line == False:
                if line.strip() == "":
                    raise RuntimeError("\"{}\" contains a blank line".format(tune_file))
                else:
                    tune_dict["ABC"] += [line]
                    categorised_line = True
    tune_dict["ABC"] = "".join(tune_dict["ABC"])
    tune_list += [tune_dict]

tune_pd = pd.DataFrame(tune_list, columns=["Type", "Time", "Time Unit", "Key", "Title", "Composer", "Source", "ABC"])
tune_pd.to_html(buf="tunelist_table.html", index=False, table_id="tunelist_table", classes=["display compact"], border=False)

100%|██████████| 3/3 [00:00<00:00, 882.89it/s]

In [ ]:
tune_pd = pd.DataFrame(tune_list, columns=["Type", "Time", "Time Unit", "Key", "Title", "Composer", "Source", "ABC"])

,Type,Time,Time Unit,Key,Title,Composer,Source,ABC
0,Jig,6/8,1/8,D,Arthur Darley's Swedish,Arthur Darley,Craig Harrison,"e|:fgf edc|d2A BAG|FED EDC|DA,B, CDE|\n\nDdd A..."
1,Jig,6/8,1/8,E,AJ's,Ian Lothian,https://thesession.org/tunes/10738,"|:~g3 fef|gfe cBc|ecB GFE|F2E CB,C|\n\n~E3 FEc..."
2,Jig,6/8,1/8,F#m,Hold Up the Sky,Brian Finnegan,Jamie Quinn,|:FAB c2B | ABc- cBA | B2c e2c | f2e cBA |\n\n...

In [31]:
lines

['X: 1\n',
 'T: Hold Up the Sky\n',
 'C: Brian Finnegan\n',
 'M: 6/8\n',
 'R: Jig\n',
 '\n',
 'L: 1/8\n',
 'S: Jamie Quinn\n',
 'K: F#m\n',
 '|:FAB c2B | ABc- cBA | B2c e2c | f2e cBA |\n',
 'FAB c2B | ABc- cBA | B2A F2E |1 F3 F2E :|2 F3 F2C ||\n',
 '|: D2F FEF | A2F D2C | B,2F FEF | B2A F2C |\n',
 '[1 EFF FEC | EFF FEF | AFA BAB | ~c3 c2C :| \n',
 '[2 AEF- FEF | AEF- FEF | AFA BAB | ~c3 c2E |]\n']